FROM python:3.14-rc-alpine
ENTRYPOINT ["python3"]
CMD ["--help"]

# The result is an image that has Python as ENTRYPOINT and 
# you can override the default command (i.e. --help) 
# with another python command, for example --version to see the version.