name: Deployment pipeline # Name of the workflow

# On a push to the main branch
on:
  push:
    branches:
      - main

# Job called build runs-on ubuntu-latest
jobs:
  deploy-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Swizzle search
        run: npm run swizzle docusaurus-lunr-search SearchBar -- --eject --danger
      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GTHUB_TOKEN }}
          publish_dir: ./build
          cname: devopswithdocker.com

  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #  Build the image and push it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: teklitdev/express-app:latest
