FROM python:3.14-rc-alpine

CMD ["python3"]

# We can open the container image in Python interactive environment
# such as docker run -it pyth-docker-cmd
# the above docker command opens Python interactive environment